// Code generated by hertz generator.

package api

import (
	"context"

	api "douyinProject/api/biz/model/api"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// MessageChatMethod .
// @router /douyin/message/chat/ [GET]
func MessageChatMethod(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.MessageChatReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.MessageChatResp)

	c.JSON(consts.StatusOK, resp)
}

// MessageSendMethod .
// @router /douyin/message/action/ [POST]
func MessageSendMethod(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.MessageSendReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.MessageSendResp)

	c.JSON(consts.StatusOK, resp)
}
