// Code generated by hertz generator.

package api

import (
	"context"

	api "douyinProject/api/biz/model/api"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// PublishActionMethod .
// @router /douyin/publish/action/ [POST]
func PublishActionMethod(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.PublishActionReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.PublishActionResp)

	c.JSON(consts.StatusOK, resp)
}

// PublishListMethod .
// @router /douyin/publish/list/ [GET]
func PublishListMethod(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.PublishListReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.PublishListResp)

	c.JSON(consts.StatusOK, resp)
}
