// Code generated by hertz generator.

package api

import (
	"context"

	api "douyinProject/api/biz/model/api"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// RegistMethod .
// @router /douyin/user/register/ [POST]
func RegistMethod(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.RegistReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.RegistResp)

	c.JSON(consts.StatusOK, resp)
}

// LoginMethod .
// @router /douyin/user/login/ [POST]
func LoginMethod(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.LoginReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.LoginResp)

	c.JSON(consts.StatusOK, resp)
}

// InfoMethod .
// @router /douyin/user/ [GET]
func InfoMethod(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.InfoReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.InfoResp)

	c.JSON(consts.StatusOK, resp)
}
